services:
  - type: web
    name: commercecraft-backend
    runtime: node
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /health
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile --prod=false --filter @apps/backend... --filter @ecom/shared... && pnpm --filter @ecom/shared build && pnpm --filter @apps/backend build
    startCommand: pnpm --filter @apps/backend start:render
    buildFilter:
      paths:
        - apps/backend/**
        - packages/shared/**
        - package.json
        - pnpm-workspace.yaml
        - turbo.json
        - tsconfig.base.json
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: commercecraft-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: RATE_LIMIT_MAX
        value: 200
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  - type: web
    name: commercecraft-frontend
    runtime: node
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile --prod=false --filter @apps/frontend... --filter @ecom/shared... && pnpm --filter @ecom/shared build && pnpm --filter @apps/frontend build
    startCommand: pnpm --filter @apps/frontend exec next start -H 0.0.0.0 -p $PORT
    buildFilter:
      paths:
        - apps/frontend/**
        - packages/shared/**
        - package.json
        - pnpm-workspace.yaml
        - turbo.json
        - tsconfig.base.json
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: BACKEND_EXTERNAL_URL
        fromService:
          type: web
          name: commercecraft-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_API_BASE_URL
        value: /api
